name: build-and-deploy
on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: harsh042/go-web-app

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # to commit the tag change
    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Install yq
        run: sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 && sudo chmod +x /usr/local/bin/yq

      - name: Update k8s image tag (GitOps)
        run: |
          NEW_IMAGE="${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          yq -i '.spec.template.spec.containers[0].image = strenv(NEW_IMAGE)' k8s/manifests/deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add k8s/manifests/deployment.yaml
          git commit -m "chore: deploy ${NEW_IMAGE}"
          git push
